import { Reveal } from "@/components/motion/primitives";

/**
 * Deliberately not fake "trusted by" customer logos — this is a portfolio
 * project, not a company with real customers, and fabricating social
 * proof would be dishonest. Instead this states true, verifiable facts
 * about how the product is actually built.
 */
const FACTS = [
  "Sourced from SEC EDGAR filings",
  "Deterministic 5-category scoring engine",
  "Explanations generated by Claude",
  "Every score is fully re-computable",
];

export function CredibilityStrip() {
  return (
    <section className="border-y border-mkt-border bg-mkt-bg py-8">
      <Reveal className="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-x-10 gap-y-3 px-6 text-center text-xs uppercase tracking-[0.15em] text-mkt-ink-subtle">
        {FACTS.map((fact) => (
          <span key={fact}>{fact}</span>
        ))}
      </Reveal>
    </section>
  );
}
